### ISSUE TITLE
merchant_secret

### ISSUE THREAD

**Issue by CharukaWijethunga** [PayHereLK/payhere-mobilesdk-flutter#10]
Why does the merchant_secret does not included in the example?

**Comment by PayHereDevs** [comment]
Hi @CharukaWijethunga, sorry for the delayed reply.

If you are using version `3.0.0` or newer, the merchant secret is no longer required to be hard-coded. Validation happens internally using your Merchant ID.

**Comment by PayHereDevs** [comment]
We will close this issue for now since we assume we have answered your question. Please feel free to comment any concerns, and we will re-open it.
