### ISSUE TITLE
ReadMe has incorrect info.

### ISSUE THREAD

**Issue by SrilalS** [PayHereLK/payhere-mobilesdk-flutter#2]
In section 2, "android:allowBackup" isn't the replacement value. it should be "android:label"

**Comment by kavin-du** [comment]
> In section 2, "android:allowBackup" isn't the replacement value. it should be "android:label"

yeah, It gives some errors when using "allowBackup". It should be corrected to "label"....

**Comment by PayHereDevs** [comment]
Hello, this changes are now incorporated into the README.md file. Thank you for pointing out the issue. The issue will be closed since it is now resolved.
