### ISSUE TITLE
IOS Problem - Merchant is not Eligable

### ISSUE THREAD

**Issue by kalindud** [PayHereLK/payhere-mobilesdk-flutter#3]
Hi,
 Sandbox works fine on IOS. But when switching to LIVE account, the following error is thrown when trying to open the payment menu.
**`One Time Payment Failed. Error: Server Response Error: This payment cannot be processed as the merchant is not eligible to accept automatic payments`**

I have created and got a separate domain for IOS package approved.
for Android, it works fine.

What could be the issue?

**Comment by PayHereDevs** [comment]
Dear Merchant, 

This error is related to the PayHere Plan you have subscribed in your PayHere Live Merchant Account. At the time of writing, PayHere Live accounts can subscribe to one of the following three packages.

1. Lite (Default package)
2. PLUS
3. PREMIUM

Each of these packages have different benefits ([reference](https://www.payhere.lk/fees)). Amongst them, the ability to process Automatic Payments through Pre-approval Requests is only granted to PREMIUM plan subscribers.

Pre-approval Requests are part of [PayHere Automated Charging](https://support.payhere.lk/faq/automated-charging). Therefore, you must subscribe to the PREMIUM plan if you are planning to use this feature in production.


Apologies for the late response, we hope you were able to solve it in due time. The issue will be closed soon if there is no response.
