### ISSUE TITLE
Works fine in the debugging version. But in the released APK, this error occurs.

### ISSUE THREAD

**Issue by nipunai7** [PayHereLK/payhere-mobilesdk-flutter#7]
![Screenshot_1627728834](https://user-images.githubusercontent.com/10683839/127737662-ae41ee41-b5f0-45df-8dda-ad501320269e.png)

**Comment by PayHereDevs** [comment]
Hello Nipuna!

This looks like an issue with Android Code Minification.

Please add the following line to your project's __"<project root>/android/app/proguard-rules.pro"__ file. 

```ruby
-keep class lk.payhere.** { *; }
```

If the "proguard-rules.pro" file does not exist, you can simply create one in the project's "<project root>/android/app" folder. 

After adding a new file, make sure it is included in the project's "<project root>/android/app/build.gradle" file as shown below (refer to the two lines after the asterisk marks)

```groovy
android {
 compileSdkVersion 29

  sourceSets {
    main.java.srcDirs += 'src/main/kotlin'
  }

  lintOptions {
    disable 'InvalidPackage'
  }

  defaultConfig {
    // Android configurations are usually here
  }

  // Signing Configurations are usually here

  buildTypes {
    release {

      signingConfig signingConfigs.debug


      minifyEnabled enableProguardInReleaseBuilds
      // ******** Add the following two lines *********
      useProguard true
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

    }
  }
}
```
